trailingComma: "all"
printWidth: 120
quoteProps: "consistent"
endOfLine: lf
arrowParens: always
plugins:
  - "@typespec/prettier-plugin-typespec"
  - "prettier-plugin-organize-imports"

overrides: [{ "files": "*.tsp", "options": { "parser": "typespec" } }]
