name: Publish
on:
  push:
    branches:
      - main
      - use-npm

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"


      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: node .github/workflows/set-prerelease-version.mjs
        name: Set prereleases versions
      - name: Publish to GitHub npm registry
        run: pnpm publish  -r --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
